server:
  port: 9909
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
    #preferIpAddress: true

spring:
  application:
    name: client
  cloud:
    config:
      enabled: false

logging:
  file:
    name: ${spring.application.name}-${server.port}.log
  level:
    org.company.project: debug
    org.springframework: warn
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 10KB
      file-name-pattern: ${spring.application.name}-${server.port}-%d{yyyy-MM-dd}.%i.log
