server.port: 9903

spring:
  application.name: person-service-find
#  jpa:
#    show-sql: true
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orclpdb1
    username: amir_read
    password: myjava123
    dbcp2:
      max-total: 20
      max-idle: 5
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: PersonService-Find_1
      properties:
        spring:
          json:
            trusted:
              packages: org.company.project.model.domain
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}

logging:
  file:
    name: ${spring.application.name}-${server.port}.log
  level:
    org.company.project: debug
    org.springframework: warn
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 10KB
      file-name-pattern: ${spring.application.name}-${server.port}-%d{yyyy-MM-dd}.%i.log