server:
  port: 9001
spring:
  application:
    name: discovery-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
     defaultZone: http://localhost:${server.port}/eureka

logging:
  file:
    name: ${spring.application.name}-${server.port}.log
  level:
    org.company.project: debug
    org.springframework: warn
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 10KB
      file-name-pattern: ${spring.application.name}-${server.port}-%d{yyyy-MM-dd}.%i.log
